import {
	WIDGET,
	WidgetRegistry,
} from '@blue-learn/schema';
import {
	Button,
	Space,
	Icon,
	Stack,
	Avatar,
	Tabs,
	Divider,
	Typography,
	TextInput,
	Card,
	Image,
	ProgressIndicator,
	Gradient,
	Chip,
	Tag,
	MemberCard,
	IcebreakerCard,
	UserCard,
	NewsCard,
	DiscussionCard,
	FeedCard,
	CommentCard,
	Grid,
	InfoCard,
	ApplicantCard,
} from './index';

const registry: WidgetRegistry = {
	[WIDGET.TEXT]: Typography,
	[WIDGET.INPUT]: TextInput,
	[WIDGET.BUTTON]: Button,
	[WIDGET.STACK]: Stack,
	[WIDGET.SPACE]: Space,
	[WIDGET.ICON]: Icon,
	[WIDGET.AVATAR]: Avatar,
	[WIDGET.TABS]: Tabs,
	[WIDGET.DIVIDER]: Divider,
	[WIDGET.CARD]: Card,
	[WIDGET.IMAGE]: Image,
	[WIDGET.PROGRESSINDICATOR]: ProgressIndicator,
	[WIDGET.GRADIENT]: Gradient,
	[WIDGET.CHIP]: Chip,
	[WIDGET.TAG]: Tag,
	[WIDGET.MEMBERCARD]: MemberCard,
	[WIDGET.ICEBREAKERCARD]: IcebreakerCard,
	[WIDGET.USERCARD]: UserCard,
	[WIDGET.NEWSCARD]: NewsCard,
	[WIDGET.DISCUSSIONCARD]: DiscussionCard,
	[WIDGET.FEEDCARD]: FeedCard,
	[WIDGET.COMMENTCARD]: CommentCard,
	[WIDGET.GRID]: Grid,
	[WIDGET.INFOCARD]: InfoCard,
	[WIDGET.APPLICANTCARD]: ApplicantCard,
};

export { registry as WidgetRegistry };
