export enum WIDGET {
	TEXT = 'TEXT',
	INPUT = 'INPUT',
	BUTTON = 'BUTTON',
	SPACE = 'SPACE',
	ICON = 'ICON',
	STACK = 'STACK',
	AVATAR = 'AVATAR',
	TABS = 'TABS',
	DIVIDER = 'DIVIDER',
	CARD = 'CARD',
}
