import {
	topBarTypeToken,
	TopBarTypeTokensMap,
} from '@blue-learn/schema';

export const topBarTypeTokensMap: TopBarTypeTokensMap =
	{
		[topBarTypeToken.mainpage]: {
			nestedTab: false,
			leftIcon: false,
			rightIcon1: false,
			rightIcon2: true,
			cta: false,
			avatar: false,
			subTitle: false,
		},
		[topBarTypeToken.mainpageWithTwoicon]: {
			nestedTab: false,
			leftIcon: false,
			rightIcon1: true,
			rightIcon2: true,
			cta: false,
			avatar: false,
			subTitle: false,
		},
		[topBarTypeToken.mainpageNestedTab]: {
			nestedTab: true,
			leftIcon: false,
			rightIcon1: false,
			rightIcon2: false,
			cta: false,
			avatar: false,
			subTitle: false,
		},
		[topBarTypeToken.subpage]: {
			nestedTab: false,
			leftIcon: true,
			rightIcon1: false,
			rightIcon2: true,
			cta: false,
			avatar: false,
			subTitle: false,
		},
		[topBarTypeToken.subpageWithTwoIcon]: {
			nestedTab: false,
			leftIcon: true,
			rightIcon1: true,
			rightIcon2: true,
			cta: false,
			avatar: false,
			subTitle: false,
		},
		[topBarTypeToken.subpageWithCta]: {
			nestedTab: false,
			leftIcon: true,
			rightIcon1: false,
			rightIcon2: false,
			cta: true,
			avatar: false,
			subTitle: false,
		},
		[topBarTypeToken.subpageWithCtaAndIcon]: {
			nestedTab: false,
			leftIcon: true,
			rightIcon1: false,
			rightIcon2: true,
			cta: true,
			avatar: false,
			subTitle: false,
		},
		[topBarTypeToken.subpageWithSubTitle]: {
			nestedTab: false,
			leftIcon: true,
			rightIcon1: true,
			rightIcon2: true,
			cta: false,
			avatar: false,
			subTitle: true,
		},
		[topBarTypeToken.subpageWithSubTitleNestedTab]:
			{
				nestedTab: true,
				leftIcon: true,
				rightIcon1: true,
				rightIcon2: true,
				cta: false,
				avatar: false,
				subTitle: true,
			},
		[topBarTypeToken.subpageWithSubTitleAndavatar]:
			{
				nestedTab: false,
				leftIcon: true,
				rightIcon1: true,
				rightIcon2: true,
				cta: false,
				avatar: true,
				subTitle: true,
			},
		[topBarTypeToken.subpageWithSubTitleAndavatarAndOneIcon]:
			{
				nestedTab: false,
				leftIcon: true,
				rightIcon1: false,
				rightIcon2: true,
				cta: false,
				avatar: true,
				subTitle: true,
			},
	};
