import {
	ButtonTypeTokens,
	ButtonTypeTokensMap,
	ColorTokens,
	BorderRadiusTokens,
	FontSizeTokens,
	ShadowTypeTokens,
	SizeTypeTokens,
} from '@blue-learn/schema';

export const buttonTypeTokensMap: ButtonTypeTokensMap =
	{
		[ButtonTypeTokens.GoogleLargeFilled]: {
			borderRadius: BorderRadiusTokens.BR1,
			labelColor: ColorTokens.White,
			bgColor: ColorTokens.Google,
			paddingVertical: SizeTypeTokens.XS,
			fontSize: FontSizeTokens.LG,
			paddingHorizontal: SizeTypeTokens.XS,
		},
		[ButtonTypeTokens.LargeFilled]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Grey_50,
			bgColor: ColorTokens.Blue_600,
			paddingVertical: SizeTypeTokens.LG,
			fontSize: FontSizeTokens.MD,
			paddingHorizontal: SizeTypeTokens.XXXXL,
		},
		[ButtonTypeTokens.MediumFilled]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Grey_50,
			bgColor: ColorTokens.Blue_600,
			paddingVertical: SizeTypeTokens.MD,
			fontSize: FontSizeTokens.SM,
			paddingHorizontal: SizeTypeTokens.XXXL,
		},
		[ButtonTypeTokens.SmallFilled]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Grey_50,
			bgColor: ColorTokens.Blue_600,
			paddingVertical: SizeTypeTokens.SM,
			fontSize: FontSizeTokens.XS,
			paddingHorizontal: SizeTypeTokens.XL,
		},
		[ButtonTypeTokens.IconFilled]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Grey_50,
			bgColor: ColorTokens.Blue_600,
			paddingVertical: SizeTypeTokens.LG,
			paddingHorizontal: SizeTypeTokens.LG,
		},
		[ButtonTypeTokens.LargeSoftFilled]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Grey_500,
			bgColor: ColorTokens.Blue_100,
			paddingVertical: SizeTypeTokens.LG,
			fontSize: FontSizeTokens.MD,
			paddingHorizontal: SizeTypeTokens.XXXXL,
		},
		[ButtonTypeTokens.MediumSoftFilled]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Grey_500,
			bgColor: ColorTokens.Blue_100,
			paddingVertical: SizeTypeTokens.MD,
			fontSize: FontSizeTokens.SM,
			paddingHorizontal: SizeTypeTokens.XXXL,
		},
		[ButtonTypeTokens.SmallSoftFilled]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Grey_500,
			bgColor: ColorTokens.Blue_100,
			paddingVertical: SizeTypeTokens.SM,
			fontSize: FontSizeTokens.XS,
			paddingHorizontal: SizeTypeTokens.XL,
		},
		[ButtonTypeTokens.IconSoftFilled]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Grey_500,
			bgColor: ColorTokens.Blue_100,
			paddingVertical: SizeTypeTokens.LG,
			paddingHorizontal: SizeTypeTokens.LG,
		},
		[ButtonTypeTokens.LargeOutline]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Blue_600,
			bgColor: ColorTokens.Transparent,
			paddingVertical: SizeTypeTokens.LG,
			fontSize: FontSizeTokens.MD,
			borderColor: ColorTokens.Grey_200,
			paddingHorizontal: SizeTypeTokens.XXXXL,
		},
		[ButtonTypeTokens.MediumOutline]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Blue_600,
			bgColor: ColorTokens.Transparent,
			paddingVertical: SizeTypeTokens.MD,
			fontSize: FontSizeTokens.SM,
			borderColor: ColorTokens.Grey_200,
			paddingHorizontal: SizeTypeTokens.XXXL,
		},
		[ButtonTypeTokens.SmallOutline]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Blue_600,
			bgColor: ColorTokens.Transparent,
			paddingVertical: SizeTypeTokens.SM,
			fontSize: FontSizeTokens.XS,
			borderColor: ColorTokens.Grey_200,
			paddingHorizontal: SizeTypeTokens.XL,
		},
		[ButtonTypeTokens.IconOutline]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Blue_600,
			bgColor: ColorTokens.Transparent,
			paddingVertical: SizeTypeTokens.LG,
			borderColor: ColorTokens.Grey_200,
			paddingHorizontal: SizeTypeTokens.LG,
		},
		[ButtonTypeTokens.LargeGhost]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Blue_600,
			bgColor: ColorTokens.Transparent,
			paddingVertical: SizeTypeTokens.LG,
			fontSize: FontSizeTokens.MD,
			paddingHorizontal: SizeTypeTokens.XXXXL,
		},
		[ButtonTypeTokens.MediumGhost]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Blue_600,
			bgColor: ColorTokens.Transparent,
			paddingVertical: SizeTypeTokens.MD,
			fontSize: FontSizeTokens.SM,
			paddingHorizontal: SizeTypeTokens.XXXL,
		},
		[ButtonTypeTokens.SmallGhost]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Blue_600,
			bgColor: ColorTokens.Transparent,
			paddingVertical: SizeTypeTokens.SM,
			fontSize: FontSizeTokens.XS,
			paddingHorizontal: SizeTypeTokens.SM,
		},
		[ButtonTypeTokens.IconGhost]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Blue_600,
			bgColor: ColorTokens.Transparent,
			paddingVertical: SizeTypeTokens.SM,
			paddingHorizontal: SizeTypeTokens.SM,
		},
		[ButtonTypeTokens.LargeElevated]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Blue_600,
			bgColor: ColorTokens.Blue_100,
			paddingVertical: SizeTypeTokens.LG,
			fontSize: FontSizeTokens.MD,
			shadow: ShadowTypeTokens.E1,
			paddingHorizontal: SizeTypeTokens.XXXXL,
		},
		[ButtonTypeTokens.MediumElevated]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Blue_600,
			bgColor: ColorTokens.Blue_100,
			paddingVertical: SizeTypeTokens.MD,
			fontSize: FontSizeTokens.SM,
			shadow: ShadowTypeTokens.E1,
			paddingHorizontal: SizeTypeTokens.XXXL,
		},
		[ButtonTypeTokens.SmallElevated]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Blue_600,
			bgColor: ColorTokens.Blue_100,
			paddingVertical: SizeTypeTokens.SM,
			fontSize: FontSizeTokens.XS,
			shadow: ShadowTypeTokens.E1,
			paddingHorizontal: SizeTypeTokens.XL,
		},
		[ButtonTypeTokens.IconElevated]: {
			borderRadius: BorderRadiusTokens.BR4,
			labelColor: ColorTokens.Blue_600,
			bgColor: ColorTokens.Blue_100,
			paddingVertical: SizeTypeTokens.LG,
			shadow: ShadowTypeTokens.E1,
			paddingHorizontal: SizeTypeTokens.LG,
		},
	};
