name: design-component

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - uses: actions/setup-node@1
        with:
          node-version:12
          registry-url: https:/npm.pkg.github.com
          scope: "@Blue-learn"
      - run: npm install
      - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{secret.GITHUB_TOKEN}}
