name: release

on:
  pull_request:
    paths:
      - .github/workflows/main.yml
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - uses: int128/release-typescript-action@v1