name: release

on:
  pull_request:
    paths:
      - .github/workflows/main.yml
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: setup git config
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
        env:
          NODE_AUTH_TOKEN: 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
        with:
          node-version: 16
          cache: yarn
          registry-url: https://npm.pkg.github.com/
          scope: "@Blue-learn"
          always-auth: true
      - run: echo ${{env.NODE_AUTH_TOKEN}}
      - run: npm version patch
      - run: npm publish