image: node:14.18.0

stages:
  - lint
  - test

cache:
  paths:
    - node_modules

before_script:
  - node -v

lint:
  stage: lint
  script:

  only:
    - merge_requests

testing:
  stage: test
  script:
    - cd ./packages/component
    - npm cache clean --force
    - npm i
    - node -v

  only:
    - merge_requests
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
