name: release

on:
    pull_request:
        paths:
            - .github/workflows/main.yml
    push:
        branches:
            - main
        tags:
            - v*

jobs:
    tag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              with:
                  node-version: 16
                  cache: npm
                  registry-url: "https://registry.npmjs.org"
                  scope: "@blue-learn"
            - run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email "<>"

            - run: npm run bootstrap

            - run: cp -a node_modules/. packages/theme/node_modules/

            - run: npm run build

            - run: npm run publish-force
