name: Storybook
on:
  push:
    branches:
      - main
jobs:
  storybook-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 16
          cache: npm
          registry-url: "https://registry.npmjs.org"
          scope: "@blue-learn"
      - run: npm run setup
      - run: lerna run build
      - run: npm run storybook-build
      - run: npm run storybook-deploy -- --ci
