name: Storybook
on:
  push:
    branches:
      - main # if any push happens on branch `main`, run this workflow. You could also add `paths` to detect changes in specific folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build Schema
        run: |
          pwd
          cd packages/schema
          npm run build
          pwd
          ls

      - name: Build Theme
        run: |
          pwd
          ls
          cd ..
          cd theme
          npm run build
          pwd

      - name: Build Component
        run: |
          cd ..
          cd component
          npm run build

      - name: Build Storybook
        run: |
          cd ..
          cd ..           
          npm run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: main
          folder: storybook-static #
