name: Storybook
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - run:  npm run setup
      - run:  lerna run build
      - run:  npm run build-storybook
      - run:  npm run deploy-storybook -- --ci
