name: Storybook
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm run setup
      - run: lerna run build
      - run: npm run storybook-build
      - run: npm run storybook-deploy -- --ci
